import Foundation

enum KeyNames {
    static let catalog: [(key: String, title: String, code: UInt16)] = [
        ("a", "A", 0),
        ("b", "B", 11),
        ("c", "C", 8),
        ("d", "D", 2),
        ("e", "E", 14),
        ("f", "F", 3),
        ("g", "G", 5),
        ("h", "H", 4),
        ("i", "I", 34),
        ("j", "J", 38),
        ("k", "K", 40),
        ("l", "L", 37),
        ("m", "M", 46),
        ("n", "N", 45),
        ("o", "O", 31),
        ("p", "P", 35),
        ("q", "Q", 12),
        ("r", "R", 15),
        ("s", "S", 1),
        ("t", "T", 17),
        ("u", "U", 32),
        ("v", "V", 9),
        ("w", "W", 13),
        ("x", "X", 7),
        ("y", "Y", 16),
        ("z", "Z", 6),
        ("0", "0", 29),
        ("1", "1", 18),
        ("2", "2", 19),
        ("3", "3", 20),
        ("4", "4", 21),
        ("5", "5", 23),
        ("6", "6", 22),
        ("7", "7", 26),
        ("8", "8", 28),
        ("9", "9", 25),
        ("minus", "Minus", 27),
        ("equal", "Equal", 24),
        ("leftbracket", "LeftBracket", 33),
        ("rightbracket", "RightBracket", 30),
        ("semicolon", "SemiColon", 41),
        ("quote", "Quote", 39),
        ("comma", "Comma", 43),
        ("period", "Dot", 47),
        ("slash", "Slash", 44),
        ("keycode:42", "BackSlash", 42),
        ("backquote", "BackQuote", 50),
        ("keycode:10", "IntlBackslash", 10),
        ("alt", "⌥ 左 Option", 58),
        ("altgr", "⌥ 右 Option", 61),
        ("control", "⌃ 左 Control", 59),
        ("rightcontrol", "⌃ 右 Control", 62),
        ("shift", "⇧ 左 Shift", 56),
        ("rightshift", "⇧ 右 Shift", 60),
        ("meta", "⌘ 左 Command", 55),
        ("rightmeta", "⌘ 右 Command", 54),
        ("capslock", "Caps Lock", 57),
        ("keycode:63", "Fn", 63),
        ("return", "Return ↵", 36),
        ("tab", "Tab ⇥", 48),
        ("space", "Space", 49),
        ("backspace", "⌫", 51),
        ("escape", "Esc", 53),
        ("delete", "⌦", 117),
        ("up", "↑", 126),
        ("down", "↓", 125),
        ("left", "←", 123),
        ("right", "→", 124),
        ("home", "Home", 115),
        ("end", "End", 119),
        ("pageup", "PageUp", 116),
        ("pagedown", "PageDown", 121),
        ("f1", "F1", 122),
        ("f2", "F2", 120),
        ("f3", "F3", 99),
        ("f4", "F4", 118),
        ("f5", "F5", 96),
        ("f6", "F6", 97),
        ("f7", "F7", 98),
        ("f8", "F8", 100),
        ("f9", "F9", 101),
        ("f10", "F10", 109),
        ("f11", "F11", 103),
        ("f12", "F12", 111),
        ("kp0", "数字键 0", 82),
        ("kp1", "数字键 1", 83),
        ("kp2", "数字键 2", 84),
        ("kp3", "数字键 3", 85),
        ("kp4", "数字键 4", 86),
        ("kp5", "数字键 5", 87),
        ("kp6", "数字键 6", 88),
        ("kp7", "数字键 7", 89),
        ("kp8", "数字键 8", 91),
        ("kp9", "数字键 9", 92),
        ("kpreturn", "数字键 Enter", 76),
        ("kpminus", "数字键 Minus", 78),
        ("kpplus", "数字键 Plus", 69),
        ("kpmultiply", "数字键 Multiply", 67),
        ("kpdivide", "数字键 Divide", 75),
        ("kpdelete", "数字键 Delete", 65),
        ("insert", "Insert", 114),
        ("numlock", "Lock", 71),
        ("printscreen", "PrintScreen", 105),
        ("scrolllock", "ScrollLock", 107),
        ("pause", "Pause", 113),
    ]
    static func fromCode(_ code: UInt16) -> String {
        catalog.first { $0.code == code }?.key ?? "keycode:\(code)"
    }
    static func title(_ key: String) -> String {
        if key.hasPrefix("keycode:"), let code = UInt16(key.dropFirst(8)) {
            return catalog.first { $0.code == code }?.title ?? "按键 \(code)"
        }
        let aliases = ["enter": "return", "cmd": "meta", "command": "meta", "ctrl": "control", "option": "alt", "esc": "escape", "rctrl": "rightcontrol", "rshift": "rightshift", "rcmd": "rightmeta"]
        let normalized = aliases[key.lowercased()] ?? key.lowercased()
        return catalog.first { $0.key == normalized }?.title ?? key.uppercased()
    }
}
